### ISSUE TITLE
Existing project

### ISSUE THREAD

**Issue by Aerijo** [thomasjo/tree-sitter-latex#1]
Hey, I was wondering if you've seen [an exisiting parser project](https://github.com/yitzchak/tree-sitter-latex) for Latex? (Though I do understand the appeal of writing [one's own](https://github.com/Aerijo/tree-sitter-latex2e)).

In this case though, I think I'll be supporting @yitzchak's, and migrate my work on the scanner there.

**Comment by thomasjo** [comment]
Thanks for the heads up! When I created this project, I searched npm and didn't find anything, so I simply assumed nobody has started working on it yet. I guess the search engine on npm is terrible :speak_no_evil:

My bandwidth is a severely limited these days, so probably a smart move to go with @yitzchak's version.
I'll keep mine active though, since creating a reasonable grammar for LaTeX will be a very interesting challenge.
